# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Reference: https://cloud.google.com/endpoints/docs/openapi/serving-apis-from-domains?hl=en

apiVersion: v1
kind: Service
metadata:
  name: esp  
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
          app: esp # change for one of a service selector run: ms-client 
  type: LoadBalancer # change ? 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp # change
    spec:
      # [START secret-1] NOTE: create secret on cluster
      volumes:
      - name: service-account-creds
        secret:
          secretName: service-account-creds
      # [END secret-1]

      containers:
      # [START esp]
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8081",
          "--service=apis.dev.appterpel.cloud.terpel.com",
          "--rollout_strategy=managed",
          "--service_account_key=/etc/nginx/creds/service-account-creds.json",

        ]
      # [END esp]

        ports:
        - containerPort: 8081

      # [START secret-2]

        volumeMounts:
          - mountPath: /etc/nginx/creds
            name: service-account-creds
            readOnly: true

      # [END secret-2]


      #- name: echo
      #  image: gcr.io/endpoints-release/echo-python:1.0
      #  ports:
      #  - containerPort: 8080
